version: "3.8"

services:
  frontend:
    image: cardeneta_web
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - .env
    networks:
      - cardeneta

networks:
  cardeneta:
    external: true
    name: cardeneta
     