version: "3.8"

services:
  backend:
    image: api_cardeneta
    container_name: api-cardeneta
    ports:
      - "3030:3030"
    build: .
    restart: always
    volumes:
      - ./db/:/app/db
      - ./files/:/app/files
    environment:
      - .env
    networks:
      - cardeneta

networks:
  cardeneta:
    external: true
    name: cardeneta
     